// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "acquisitionctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CAcquisitionctrl1

IMPLEMENT_DYNCREATE(CAcquisitionctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAcquisitionctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CAcquisitionctrl1 operations
